#include "../../../drv_common.h"

#if PRI_FP_VDD_PMIC
#define	FP_VDD_REG mt6377_vfp
#endif

#if PRI_MICROARRAY_V4_0_0_1_CONFIG_1
#define SPI_INDEX spi1
#define FP_IRQ_PIN 15

#define FPC_PINS_EINT_AS_INT PINMUX_GPIO15__FUNC_GPIO15
#define FPC_PINS_RST         PINMUX_GPIO7__FUNC_GPIO7

#define FPC_MODE_AS_CS   PINMUX_GPIO61__FUNC_SPI1_CSB
#define FPC_MODE_AS_CK   PINMUX_GPIO60__FUNC_SPI1_CLK
#define FPC_MODE_AS_MI   PINMUX_GPIO63__FUNC_SPI1_MI
#define FPC_MODE_AS_MO   PINMUX_GPIO62__FUNC_SPI1_MO
#define FPC_MISO_PULL_UP_DOWN  PINMUX_GPIO63__FUNC_GPIO63
#define FPC_MOSI_PULL_UP_DOWN  PINMUX_GPIO62__FUNC_GPIO62
#endif