# Makefile for the fingerprint driver.

obj-$(CONFIG_FINGERPRINT_FOCALTECH)	+= focaltech_fp/
obj-$(CONFIG_FINGERPRINT_FOCALTECH_REE_ATA)	+= focaltech_ree_ata/
obj-$(CONFIG_FINGERPRINT_FORTSENSE)	+= fortsense_driver_all_in_one/
# drv add-liaoxingen-20230114-start
obj-$(CONFIG_GOODIX_GW9518_FINGERPRINT) += goodix-gw9518/
# drv add-liaoxingen-20230114-end
#prize add dengzhiyuan 20240418 start
obj-$(CONFIG_FT9399_FINGERPRINT_TEE) += focaltech_fp/
obj-$(CONFIG_MICROARRAY_FP_V4_0_0_1) += microarray_v4_0_0_1/
#prize add dengzhiyuan 20240418 end

#prize add by dengbinggui  20240927 start 
obj-$(CONFIG_PRI_FINGER_ATA_NODE) += pri_finger_ftm_node/
#prize add by dengbinggui  20240927 end